### ISSUE TITLE
A bug in read_mesh() when reading triangles

### ISSUE THREAD

**Issue by vsnever** [cg3hci/py3DViewer#11]
I think, there is a bug in the line 79:
https://github.com/cg3hci/py3DViewer/blob/7ae1697aa4860430d0d94b854f8b1f2a4b2d895f/Py3DViewer/utils/IO.py#L76-L80
It should be ` a, b, c = list(map(lambda x: int(x) - 1, line.split()[:-1])` instead.

Currently, processing any .mesh file with a "Triangles" section throws a ValueError.
```
    a, b, c, d = list(map(lambda x: int(x) - 1, line.split()[:-1]))
ValueError: not enough values to unpack (expected 4, got 3)
```

**Comment by pizza1994** [comment]
You are right, I'm fixing it now

**Comment by pizza1994** [comment]
Fixed in the last [commit](https://github.com/cg3hci/py3DViewer/commit/442305ea967c8e6a654e1dfad4f4e753e5927acb)

**Comment by vsnever** [comment]
Thanks!
