### ISSUE TITLE
Loading Hex Mesh

### ISSUE THREAD

**Issue by nicolasdonati** [cg3hci/py3DViewer#12]
Hi,
Thanks for these tools !

I am trying to load hex meshes with `Hexmesh(filename=None, vertices=V, polys=F)`
with V = N x 3 numpy array
and  F = M x 8 numpy array

For some reason this leads to the error: 

```
----> 3 X = Hexmesh(vertices=V, polys=F)
---> 61 self.__load_operations()
--> 110 self._AbstractMesh__adj_poly2poly = get_connectivity_info_volume_hex(self.num_vertices, self.polys) 

TypeError: No matching definition for argument type(s) int64, array(int32, 2d, C)
```

Which I have not been able to solve

I would like to load hexmeshes directly from files. I have seen that Py3DViewer can work with .mesh extension. Is there a .mesh writer ? I guess you would first need a mesh object, which I can't obtain, I am stuck with my numpy arrays (parsed from .vtk or other ascii extensions). 

Thanks a lot for your answer,

**Comment by pizza1994** [comment]
Hi, 
could you provide me the vtk file and the code you are using to parse the data? The library has a .mesh writer but unfortunately it cannot read .vtk yet

**Comment by nicolasdonati** [comment]
Hi !
in the end I simply used the doc to write a .mesh exporter for my data, and the loader works fine from there,
Thanks !
