### ISSUE TITLE
Divide by zero error (does not seem to cause any problems)

### ISSUE THREAD

**Issue by R7President** [cg3hci/py3DViewer#5]
The following 2 error messages comes up fairly frequently for me.

/usr/local/lib/python3.6/site-packages/Py3DViewer/utils/load_operations.py:334: RuntimeWarning: invalid value encountered in true_divide
  face_normals = cross / np.linalg.norm(cross, axis=1, keepdims=True)

/usr/local/lib/python3.6/site-packages/Py3DViewer/utils/metrics.py:46: RuntimeWarning: invalid value encountered in true_divide
  r = (2 * a) / (l1 + l2 + l3)

It doesn't seem to cause any problems, it appears that these calculations are not used.
They appear to be stats like aspect ratio of the triangles and normals.
If they are not being used then stop calculating them.
If they are being used can you disable the warnings?

Note that the warnings do not always come up, even when you re-calculate the exact same values.

It would be nice to get rid of warnings.

**Comment by pizza1994** [comment]
They are used so I can't avoid these calculations. I have silenced the warning
