### ISSUE TITLE
color_internal error

### ISSUE THREAD

**Issue by R7President** [cg3hci/py3DViewer#6]
When doing Picker on a mesh you get an error message that color_internal is not defined
it looks like a minor change is required to GUI.py to add in a check that is included everywhere else color_internal is referenced:

    def __update_internal_color(self, change): 
        if hasattr(self.mesh, "internals"): 
            self.drawable.update_internal_color(colors.hex2rgb(self.color_internal.value))

**Comment by pizza1994** [comment]
Fixed, thank you
