### ISSUE TITLE
traits.py:203 UserWarning: 64-bit data types not supported 

### ISSUE THREAD

**Issue by R7President** [cg3hci/py3DViewer#7]
/usr/local/lib/python3.6/site-packages/pythreejs/traits.py:203: UserWarning: 64-bit data types not supported for WebGL data, casting to 32-bit.
  warnings.warn('64-bit data types not supported for WebGL '

I think that this warning can be avoided if DrawableMesh.py:95 is changed from:
        interleaved = np.concatenate((tris, new_colors, vtx_normals), axis=1)
to:
        interleaved = np.concatenate((tris, new_colors, vtx_normals), axis=1).astype(float32)

**Comment by pizza1994** [comment]
Fixed
