### ISSUE TITLE
warning on initial import

### ISSUE THREAD

**Issue by R7President** [cg3hci/py3DViewer#8]
The warning:
/usr/local/lib/python3.6/site-packages/numba/core/decorators.py:153: NumbaDeprecationWarning: The 'target' keyword argument is deprecated.
  warnings.warn("The 'target' keyword argument is deprecated.", NumbaDeprecationWarning)

can be avoided if you change:
smoothing.py:21 
from:
@jit(target='cpu', nopython=True, parallel=True, cache=True)
to:
@jit(nopython=True, parallel=True, cache=True)

**Comment by pizza1994** [comment]
Thanks, fixed
